config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes, only: [:index] do
    get 'bookmark'
    get 'unbookmark'
    get 'list_bookmarked_recipes', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
require 'open-uri'
require 'nokogiri'

class RecipesController < ApplicationController
  def index
    #@recipes = Recipe.all
    if Recipe.where(day_bookmark: true).present?
      @recipes = Recipe.where(day_bookmark: true)
    else
      @recipes = Recipe.limit(1).order("RANDOM()")
    end
  end

  def bookmark
    @recipe = Recipe.find(params[:recipe_id])
    @recipe.update(saved: true, save_at: Date.today, day_bookmark: true)
    # @recipe.save!
    redirect_to recipes_path
  end

  def list_bookmarked_recipes
    @recipes = Recipe.where(saved: true)
    #redirect_to list_bookmarked_recipes_recipes_path
  end

  def unbookmark
    @recipe = Recipe.find(params[:recipe_id])
    @recipe.update(saved: false, day_bookmark: false)
    redirect_to list_bookmarked_recipes_recipes_path
  end

  # def destroy
  #   @recipe = Recipe.find(params[:id])
  #   @recipe.destroy
  #   redirect_to recipes_path
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user).deliver_now

        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">

    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>Happy <%= Date.today.strftime("%A")%> !</h1>
<p>Some ideas for cooking tonight</p>

<% @recipes.each do |recipe| %>
<ul>
  <li class="list-index-recipes">
    <h3><%= link_to recipe.name, recipe.link, target: "_blank" %></h3>
    <%= image_tag "http://#{recipe.picture}", class: "recipe_image" %> <br>
    <%#= image_tag 'http://power.itp.ac.cn/~jmyang/funny/fun4.jpg', class: "recipe_image" %> <br>
    <% unless recipe.difficulty.blank? %>
      <i class="fas fa-eye"></i> Difficulty: <%= recipe.difficulty %> <br>
    <% end %>
    <% unless recipe.difficulty.blank? %>
      <i class="far fa-clock"></i> Time: <%= recipe.time unless recipe.time.nil?  %><br>
    <% end %>
    <br>
    <div class="actions">
      <% if recipe.day_bookmark == true %>
        <i class="fas fa-bookmark"></i> Bookmarked!
        <br>
        <i class="fas fa-times"></i><%= link_to "Unmark!", recipe_unbookmark_path(recipe) %>
      <% else %>
      <i class="far fa-bookmark"></i> <%= link_to "Bookmark for today!", recipe_bookmark_path(recipe) %>
      <br>
      <br>
      <i class="fas fa-sync-alt"> </i> <%= link_to 'Next idea!', root_url %>
      <% end %>
    </div>
  </li>
</ul>
<% end %>

<%= link_to "See all my recipes", list_bookmarked_recipes_recipes_path %>

app/views/recipes/list_bookmarked_recipes.html.erb
<h1>Happy <%= Date.today.strftime("%A")%> !</h1>
<p> All recipes</p>
<i class="fas fa-chevron-circle-left"></i> <%= link_to 'Back', root_url %>

<div class="container">
  <div class="row">
      <% @recipes.each do |recipe| %>
      <ul>
        <div class="col-sm">
        <li class="list-recipes">
          <h4><%= link_to recipe.name, recipe.link, target: "_blank" %></h4>
          <h4>Cooked on <%= recipe.save_at.strftime("%B %d")%> </h4>
          <div class="recipe_details">
            <%= image_tag "http://#{recipe.picture}", class: "recipe_image" %> <br>
            <%#= image_tag 'http://power.itp.ac.cn/~jmyang/funny/fun4.jpg', class: "recipe_image" %> <br>
            <% unless recipe.difficulty.blank? %>
              <i class="fas fa-eye"></i> Difficulty: <%= recipe.difficulty %> <br>
            <% end %>
            <% unless recipe.difficulty.blank? %>
              <i class="far fa-clock"></i> Time: <%= recipe.time unless recipe.time.nil?  %><br>
            <% end %>
            <br>
            <%= link_to "Remove from my recipes", recipe_unbookmark_path(recipe) %>
          </div>
        </li>
        <i class="fab fa-pagelines"></i>
        </div>
      </ul>
      <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<%= form_for @recipe do |f| %>
  <%= f.text_field :name %>
   <%= f.submit %>
<% end %>

<hr>
<%= debug @recipe %>

app/views/recipes/show.html.erb
<%= @recipe.name %>